version : "3"
services:
  ggwp-be-api:
    build:
      context: .
      dockerfile: dockerfiles/Api.Dockerfile
    container_name: ggwp-be-api
    depends_on:
      - ggwp-be-pg
#      - ggwp-be-es
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2612:80"
    networks:
      ggwp-be-network:
        ipv4_address: 26.226.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  ggwp-be-pg:
    image: postgres:15
    container_name: ggwp-be-pg
    volumes:
      - ggwp-be-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      ggwp-be-network:
        ipv4_address: 26.226.1.2

  ggwp-be-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: ggwp-be-mailpit
    restart: always
    ports:
        - '${FORWARD_MAILPIT_PORT:-2613}:1025'
        - '${FORWARD_MAILPIT_DASHBOARD_PORT:-2614}:8025'
    networks:
      ggwp-be-network:
        ipv4_address: 26.226.1.3

  ggwp-be-q:
    build:
      context: .
      dockerfile: dockerfiles/QueueListener.Dockerfile
    container_name: ggwp-be-q
    depends_on:
      - ggwp-be-api
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      ggwp-be-network:
        ipv4_address: 26.226.1.4

#  ggwp-be-es:
#    image: elasticsearch:7.17.12
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - ggwp-be-elasticsearch-disk:/usr/share/elasticsearch/data
#    networks:
#      ggwp-be-network:
#        ipv4_address: 10.10.1.7

#  ggwp-be-0x:
#    build:
#      context: .
#      dockerfile: dockerfiles/0x.Dockerfile
#    container_name: ggwp-be-0x
#    depends_on:
#      - ggwp-be-api
#    volumes:
#      - .:/var/www/html
#    restart: always
#    networks:
#      ggwp-be-network:
#        ipv4_address: 10.10.1.5

  ggwp-be-fe-app:
    build:

      context: .
      dockerfile: dockerfiles/FeApp.Dockerfile
    container_name: ggwp-be-fe-app
    ports:
      - "1001:3000"
    volumes:
      - ./fe-app:/var/www/html
      #- ./dockerfiles:/var/www/html/dockerfiles
    restart: always
    networks:
      ggwp-be-network:
        ipv4_address: 26.226.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  ggwp-be-pg-disk: {}
  ggwp-be-elasticsearch-disk:
    driver: local

# Local network for services running using this docker-compose config
networks:
  ggwp-be-network:
    ipam:
      driver: default
      config:
        - subnet: 26.226.0.0/16
