version: 2.1
jobs:
  ci:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    working_directory: ~/code
    environment:
      - COMMITS_CHECK_ENDPOINT: https://api.reviewee.it/repository/fl-laravel_boilerplate/haveRejectedCommits
      - COMMITS_CHECK_INDICATOR: \"success\":true
    steps:
      - checkout
      - run:
          name: Check Rejected Commits
          command: wget ${COMMITS_CHECK_ENDPOINT} -q -O - | grep -q ${COMMITS_CHECK_INDICATOR}
      - run:
          name: Docker compose
          command: docker-compose up -d

      - run:
          name: CI checks
          command: docker-compose exec lbp-api composer run ci

  cd:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Heroku deploy
          command: git push --force https://heroku:$HEROKU_AUTH_KEY@git.heroku.com/$HEROKU_UAT_APP_NAME.git HEAD:refs/heads/master

workflows:
  version: 2
  ci-cd:
    jobs:
      - ci
#      - cd:
#          requires:
#            - ci
